### ISSUE TITLE
NodeBox fails to start under Turkish locale

### ISSUE THREAD

**Issue by fdb** [nodebox/nodebox#400]
This error appears when trying to start NodeBox on a machine with Turkish locale:

    java.lang.IllegalArgumentException: 
    No enum constant nodebox.node.Port.Widget.POİNT 
    at java.lang.Enum.valueOf(Unknown Source) 
    at nodebox.node.Port$Widget.valueOf(Unknown Source) 
    at nodebox.node.Port.parseWidget(Unknown Source) 
    at nodebox.node.Port.withParsedAttribute(Unknown Source) 
    at nodebox.node.NodeLibrary.parsePort(Unknown Source) 
    at nodebox.node.NodeLibrary.parseNode(Unknown Source) 
    at nodebox.node.NodeLibrary.parseNode(Unknown Source) 
    at nodebox.node.NodeLibrary.parseNDBX(Unknown Source) 
    at nodebox.node.NodeLibrary.load(Unknown Source) 
    at nodebox.node.NodeLibrary.load(Unknown Source) 
    at nodebox.client.Application.systemLibrary(Unknown Source) 
    at nodebox.client.Application.lookForLibraries(Unknown Source) 
    at nodebox.client.Application.initPython(Unknown Source) 
    at nodebox.client.Application.initApplication(Unknown Source) 
    at nodebox.client.Application.access$000(Unknown Source) 
    at nodebox.client.Application$1.doInBackground(Unknown Source) 
    at nodebox.client.Application$1.doInBackground(Unknown Source) 
    at javax.swing.SwingWorker$1.call(Unknown Source) 
    at java.util.concurrent.FutureTask.run(Unknown Source) 
    at javax.swing.SwingWorker.run(Unknown Source) 
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) 
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) 
    at java.lang.Thread.run(Unknown Source)

**Comment by fdb** [comment]
This looks like a locale / Unicode issue. The error message displayed above uses the word "POİNT", with the dot on the uppercase "I". I expect NodeBox to look for an internal constant called "POINT", without the dot.

I've dug a bit deeper and discovered that the names of the widgets get converted from lowercase ("point") to uppercase ("POINT") using the to String.toUpperCase method. Apparently, this method uses the default system locale, which in the Turkish version adds the dot.

We should make to sure to use US locale when converting uppercase to/from lowercase.
