### ISSUE TITLE
Error null on Windows

### ISSUE THREAD

**Issue by yuan0** [nodebox/nodebox#432]
There is a problem when I finished installing the NodeBox. When I open it, the console shows the error as below.
Some of the nodes work well, but some does not. I have found that the Translate and the Reflect were not working as the console show the error——cannot create PyString with non-byte value.

Traceback (most recent call last):
  File "G:\design\NB\app\nodebox.jar\Lib\site.py", line 585, in <module>
  File "G:\design\NB\app\nodebox.jar\Lib\site.py", line 567, in main
  File "G:\design\NB\app\nodebox.jar\Lib\site.py", line 300, in addusersitepackages
  File "G:\design\NB\app\nodebox.jar\Lib\site.py", line 289, in getusersitepackages
  File "G:\design\NB\app\nodebox.jar\Lib\sysconfig.py", line 416, in get_path
  File "G:\design\NB\app\nodebox.jar\Lib\sysconfig.py", line 407, in get_paths
  File "G:\design\NB\app\nodebox.jar\Lib\sysconfig.py", line 180, in _expand_vars
  File "G:\design\NB\app\nodebox.jar\Lib\sysconfig.py", line 154, in _subst_vars
  File "G:\design\NB\app\nodebox.jar\Lib\sysconfig.py", line 154, in _subst_vars
UnicodeEncodeError: 'ascii' codec can't encode character u'\u73b2' in position 9: ordinal not in range(128)

	at org.python.core.codecs.strict_errors(codecs.java:208)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.python.core.JavaFunc.__call__(Py.java:2426)
	at org.python.core.PyObject.__call__(PyObject.java:431)
	at org.python.core.codecs.encoding_error(codecs.java:1538)
	at org.python.core.codecs.PyUnicode_EncodeIntLimited(codecs.java:1211)
	at org.python.core.codecs.PyUnicode_EncodeASCII(codecs.java:1170)
	at org.python.core.codecs.encode(codecs.java:165)
	at org.python.core.PyString.encode(PyString.java:3896)
	at org.python.core.PyString.encode(PyString.java:3888)
	at org.python.core.PyUnicode.unicode___str__(PyUnicode.java:667)
	at org.python.core.PyUnicode.__str__(PyUnicode.java:662)
	at org.python.core.PyString.buildFormattedString(PyString.java:4006)
	at org.python.core.PyString.str_format(PyString.java:3941)
	at org.python.core.PyString$str_format_exposer.__call__(Unknown Source)
	at org.python.core.PyObject._callextra(PyObject.java:601)
	at sysconfig$py._subst_vars$3(G:\design\NB\app\nodebox.jar\Lib\sysconfig.py:159)
	at sysconfig$py.call_function(G:\design\NB\app\nodebox.jar\Lib\sysconfig.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:167)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:153)
	at org.python.core.PyFunction.__call__(PyFunction.java:423)
	at sysconfig$py._expand_vars$5(G:\design\NB\app\nodebox.jar\Lib\sysconfig.py:181)
	at sysconfig$py.call_function(G:\design\NB\app\nodebox.jar\Lib\sysconfig.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:167)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:153)
	at org.python.core.PyFunction.__call__(PyFunction.java:423)
	at sysconfig$py.get_paths$17(G:\design\NB\app\nodebox.jar\Lib\sysconfig.py:409)
	at sysconfig$py.call_function(G:\design\NB\app\nodebox.jar\Lib\sysconfig.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:167)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:170)
	at org.python.core.PyFunction.__call__(PyFunction.java:434)
	at sysconfig$py.get_path$18(G:\design\NB\app\nodebox.jar\Lib\sysconfig.py:416)
	at sysconfig$py.call_function(G:\design\NB\app\nodebox.jar\Lib\sysconfig.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:167)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:307)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:145)
	at org.python.core.PyFunction.__call__(PyFunction.java:423)
	at site$py.getusersitepackages$10(G:\design\NB\app\nodebox.jar\Lib\site.py:290)
	at site$py.call_function(G:\design\NB\app\nodebox.jar\Lib\site.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:167)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:124)
	at org.python.core.PyFunction.__call__(PyFunction.java:403)
	at site$py.addusersitepackages$11(G:\design\NB\app\nodebox.jar\Lib\site.py:304)
	at site$py.call_function(G:\design\NB\app\nodebox.jar\Lib\site.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:167)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:138)
	at org.python.core.PyFunction.__call__(PyFunction.java:413)
	at site$py.main$34(G:\design\NB\app\nodebox.jar\Lib\site.py:583)
	at site$py.call_function(G:\design\NB\app\nodebox.jar\Lib\site.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:167)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:124)
	at org.python.core.PyFunction.__call__(PyFunction.java:403)
	at site$py.f$0(G:\design\NB\app\nodebox.jar\Lib\site.py:637)
	at site$py.call_function(G:\design\NB\app\nodebox.jar\Lib\site.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:167)
	at org.python.core.PyCode.call(PyCode.java:18)
	at org.python.core.imp.createFromCode(imp.java:436)
	at org.python.core.util.importer.importer_load_module(importer.java:109)
	at org.python.modules.zipimport.zipimporter.zipimporter_load_module(zipimporter.java:163)
	at org.python.modules.zipimport.zipimporter$zipimporter_load_module_exposer.__call__(Unknown Source)
	at org.python.core.PyBuiltinMethodNarrow.__call__(PyBuiltinMethodNarrow.java:46)
	at org.python.core.imp.loadFromLoader(imp.java:587)
	at org.python.core.imp.find_module(imp.java:537)
	at org.python.core.imp.import_next(imp.java:840)
	at org.python.core.imp.import_first(imp.java:861)
	at org.python.core.imp.load(imp.java:716)
	at org.python.core.Py.importSiteIfSelected(Py.java:1558)
	at org.python.util.PythonInterpreter.<init>(PythonInterpreter.java:116)
	at org.python.util.PythonInterpreter.<init>(PythonInterpreter.java:94)
	at org.python.util.PythonInterpreter.<init>(PythonInterpreter.java:71)
	at nodebox.client.Console.<init>(Console.java:70)
	at nodebox.client.Application.showConsole(Application.java:319)
	at nodebox.client.NodeBoxMenuBar$ShowConsoleAction.actionPerformed(NodeBoxMenuBar.java:587)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.JToggleButton$ToggleButtonModel.setPressed(JToggleButton.java:308)
	at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
	at javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:833)
	at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:877)
	at java.awt.Component.processMouseEvent(Component.java:6533)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6298)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by fdb** [comment]
First of: which version of NodeBox are you using?

I assume the nodes that are failing are the ones written in Python (e.g. import svg). 

This often happens on systems where the home directory contains non-ASCII characters. Can you confirm if this is the case?

**Comment by yuan0** [comment]
I'm using version 3.0.46 and my user directory is in non-ASCII characters.
Your assumption must be right!
Is there any way to solve the problem?
Thanks a lot for attention to this matter.

**Comment by fdb** [comment]
You might look at the new version 3.0.47, though I doubt it will behave differently:

https://github.com/nodebox/nodebox/releases/tag/v3.0.47
