### ISSUE TITLE
Unable to use menus on Linux

### ISSUE THREAD

**Issue by villares** [nodebox/nodebox#461]
I'm on Manjaro Linux (a distro from the Arch family), so I have cloned the project and used `ant run` as instructed.

```
$ ant run
Buildfile: /home/villares/GitHub/nodebox/build.xml

properties:

init:

compile:

bindir-unix:

bindir-win:

bindir:

run:
     [java] Jun 02, 2024 8:45:19 PM nodebox.Log info
     [java] INFO: Starting NodeBox
     [java] Jun 02, 2024 8:45:21 PM nodebox.Log warn
     [java] WARNING: Update checker encountered error.
     [java] java.io.FileNotFoundException: https://secure.nodebox.net/app/nodebox/appcast.xml?v=3.0.53&p=3
     [java] 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:2018)
     [java] 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1611)
     [java] 	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:224)
     [java] 	at nodebox.versioncheck.UpdateChecker.run(UpdateChecker.java:30)
     [java] 

BUILD SUCCESSFUL
Total time: 11 minutes 34 seconds
```
I can't use any menu command, they open an close immediately...

**Comment by villares** [comment]
Trying to follow the other Arch installation instructions on the read-me I always get an error:
```
git clone https://aur.archlinux.org/nodebox-git.git
cd nodebox-git
makepkg
sudo pacman -U nodebox-git-[version-number]-any.pkg.tar.xz
```
The first `git clone` works, then on `makepk`:

```terminal
$ cd nodebox-git/
$ makepkg
==> Making package: nodebox-git 3.0.44.x-2 (seg 03 jun 2024 18:55:51)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Cloning nodebox git repo...
Cloning into bare repository '/home/villares/GitHub/nodebox-git/nodebox'...
fatal: unable to connect to github.com:
github.com[0: 20.201.28.151]: errno=Connection timed out

==> ERROR: Failure while downloading nodebox git repo
    Aborting...
```
